version: "3"

services:
  api:
    build:
      context: src/VSPoll.API/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    env_file: .env
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - vspoll-postgres:/var/lib/docker-volumes/vspoll-postgres

volumes:
  vspoll-postgres:
